### ISSUE TITLE
Just trying to help

### ISSUE THREAD

**Issue by xPythh** [polybiusproxy/open-ribbon#1]
I am not sure If i am able to help since you are trying to decompile the PSX file of Vib Ribbon (Are they different compared to the .cue & .bin files used by emulators

Here are some informations that may help (somehow):
MAIN_T.EXE [AKA Title] Is the main menu of the game
MAIN_K.EXE [AKA Kioske] is the tutorial of the game (How to play)
MAIN_G.EXE [AKA Game] is the game itself.

I am not an expert in decompilation, but here are some informations about some of the game structure I found while digging (C++)
Title:
Starting Function name is Title main()

game/Movie.h  <- The only header file of the Title

game/VideoSys.cpp
game/CdSys.cpp
game/MemorySys.cpp
game/AudioSys.cpp
game/InputSys.cpp
game/FileSys.cpp
game/PackedFiles.cpp <- Probably has the list of the packed files of the game [.PAK] (Thoses have already been succesfully extracted)
game/InputControl.cpp
game/TmdLineObj.cpp
game/Message.cpp
game/FontHack.cpp
[ Maybe are there more ? probably ]

Game:
Starting Function name is Game main()

game/StaticQueue.h  <- The only header file of the Game

game/GameCamera.cpp <- Probably handling the inclinaison of the camera, I found a residue of a probably matching method
        ~ CGameCamera::Update()      Extra Residue:   warning: CGameCamera::Update() before first camera event
game/FbStream.cpp
game/VideoSys.cpp
game/CdSys.cpp
       ~ PlayTrack() <- Probably a method to start a game      Extra Residues: CdSys::PlayTrack(): requested track out of range
game/AudioSys.cpp
game/Thread.cpp
game/InputSys.cpp
game/MemorySys.cpp <- I found the residues of probably matching methods
      ~ malloc()
      ~ Info()
game/FileSys.cpp
game/AudioStream.cpp
game/SignalModule.cpp <- Maybe is kind of of an event system ? I found the residues of probably matching methods 
     ~ _BufferTrackEnd()  <- Not sure for this one_
     ~ SignalGameOver()
     ~ SignalUserAbort()
     ~ SignalGameClear()
game/InputControl.cpp
game/FastAllocator.cpp < - I may have found something related to the FastAllocator, the .cpp has probably multiples classes
     ~ MemoryPool::~MemoryPool()

game/Forms.cpp <- Maybe related to the character form ? Vibri, Snake, Worm, Princess
game/TitleDraw.cpp
game/AnalysisScript.cpp <- The program that convert the cd audio in waves ? or related to the PAK'ed file named **script/system3.fsl**
game/Gameplay.cpp I found the residue of a probably matching function
      ~ Gameplay::AddEvent()       Extra Residue:   Gameplay::AddEvent() : part event rejected (before start pos)
game/SceneDraw.cpp
game/RoadSelect.cpp <- Roads are maps, since the game was created originally for Mercedez, they didnt renamed thoses I think
game/Glue.cpp
      ~ Potential file     Extra Residue:   BufferTrackEnd(): bad state
game/FontHack.cpp
game/Message.cpp
[ Maybe are there more ? probably ]

Hope my informations may be usefull, some of my informations are just guesses and should be taken carefully.

**Comment by AnOpenSauceDev** [comment]
I just grabbed all the strings from the game, then regex'ed for some common PSX filetypes, for anyone curious.
[strings-regexed.txt](https://github.com/polybiusproxy/open-ribbon/files/12368047/strings-regexed.txt).
Just about everything, even Vibri's... ribbon? is a model file as well: `ROAD/ROAD.TMD`, unless this is a leftover from the Mercedes demo.

**Comment by xPythh** [comment]
> 

Indeed, even Vibris is a model ! Someone found a way to extract and read thoses files (and even running them on BLENDER !
Here is what he told me via DM

> If you just want the Vibri's model, it's been uploaded to the models resource website to download. https://models-resource.com/playstation/vibribbon/
If you still want to extract pak files and/or play around with the game's animation files, then it's a process.
There's no GUI for the program, can only be run from a CMD or Powershell window. Basically, when you find a pak file you wanna extract, paste the program into where the pak file is, open a CMD/powershell window that's pointing to the right directory, and then enter the command to extract the pak file. EX: vibripper u FILES.PAK FILES_EXT .
Step 3. Extracting or porting the models. Next part depends on what you wanna do. If you're gonna port them to blender, then consider this blender plugin: https://github.com/Murugo/Misc-Game-Research/tree/main/PS1/Vib-Ribbon . You can easily port the models in, as well as all the animations and camera angles/animations. It's as accurate as you can get, and what I recommend even if you don't wanna use blender for your purpose, since you can then export the result to whatever you need. However, if you insist on not using blender, TMD2LWO https://zophar.net/utilities/psxutil/tmd2lwo.html and a program that can read LWO (LightWave Objects) will be needed. Use TMD2LWO the same way as Vib-Ripper was used. EX: TMD2LWO.EXE MODEL.TMD WORM .

**Comment by AnOpenSauceDev** [comment]
> Indeed, even Vibris is a model ! Someone found a way to extract and read thoses files (and even running them on BLENDER ! Here is what he told me via DM

I noticed this too, but the game's own font being one big TMD object for me is far more interesting.

**Comment by xPythh** [comment]
> > Indeed, even Vibris is a model ! Someone found a way to extract and read thoses files (and even running them on BLENDER ! Here is what he told me via DM
> 
> I noticed this too, but the game's own font being one big TMD object for me is far more interesting.

We can prolly talk about this futher, check the readme if you want to join the discord, its free +1
